### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes

### ISSUE THREAD

**Issue by leeseetja** [kleok/FLOMPY#6]
I have been trying to figure out the error I keep getting on the final step of **Floodwater_classification** which has to do with `non-empty take from an empty axes`. I've looked at the numpy function relating to this error, and still can't figure out where it's coming from within the Flompy dataset.

Please find attached the error I keep getting. Any suggestions on how to go around this will be helpful.
![index_error](https://user-images.githubusercontent.com/57126813/181179716-75f03e13-4ce6-48fa-b6b6-7ffdec5aef4b.png)

**Comment by leeseetja** [comment]
Hi @kleok  , issue #1 made me realise where the issue might be. Apart from the none availability of the sat image for the event date, your discussion and explanation there was helpful. So this issue can be closed, as after adjustments it managed to run.

Thanks so much. I'm looking forward to seeing the development and usage of this tool grow!

**Comment by kleok** [comment]
Hello @leeseetja, I am glad that issue #1 helped you to tackle this issue. Your feedback is valuable and important for future improvements and development :blush: I will keep you informed for further developments :smiley:
